changeLogFile: dbchangelog.xml

url=jdbc:postgresql://dpg-d99th7t7vvec7387tjgg-a.virginia-postgres.render.com/tarakki_prod
username=tarakki
password=7ZFFWURHyVfWgo5OxzC6xS5CKO3Tq3J5
driver=org.postgresql.Driver
